<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.muziseo</groupId>
        <artifactId>start-services</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>start-service-system</artifactId>
    <description>
        system 模块下，我们放通用业务，支撑上层的核心业务。
        例如说：用户、部门、权限、数据字典等等
    </description>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-env</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-db</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>


        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-service-system-api</artifactId>
            <version>${revision}</version>
        </dependency>


        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-seata</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-sentinel</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-satoken</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-excel</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-oss</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-log</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-satoken-integration</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.muziseo</groupId>
            <artifactId>start-common-social</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

        <!-- 单元测试依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>