-- ----------------------------
-- 1. 审计操作日志表
-- ----------------------------
DROP TABLE IF EXISTS public.system_oper_log;
CREATE TABLE public.system_oper_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           CHARACTER VARYING(50)  NOT NULL DEFAULT '',               -- 模块标题
    business_type   SMALLINT               NOT NULL DEFAULT 0,                -- 业务类型
    method          CHARACTER VARYING(128) NOT NULL DEFAULT '',               -- 方法名称
    request_method  CHARACTER VARYING(10)  NOT NULL DEFAULT '',               -- 请求方式
    operator_type   SMALLINT               NOT NULL DEFAULT 0,                -- 操作类别
    oper_name       CHARACTER VARYING(50)           DEFAULT '',               -- 操作人员
    dept_name       CHARACTER VARYING(50)           DEFAULT '',               -- 部门名称
    oper_url        CHARACTER VARYING(512)          DEFAULT '',               -- 请求URL
    oper_ip         CHARACTER VARYING(128)          DEFAULT '',               -- 操作地址
    oper_location   CHARACTER VARYING(255)          DEFAULT '',               -- 操作地点
    oper_param      TEXT,                                                     -- 请求参数
    json_result     TEXT,                                                     -- 返回结果
    status          SMALLINT               NOT NULL DEFAULT 0,                -- 操作状态 (0=正常, 1=异常)
    error_msg       TEXT,                                                     -- 错误消息
    cost_time       BIGINT                 NOT NULL DEFAULT 0,                -- 耗时 (毫秒)
    create_time     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP -- 操作时间
);

COMMENT ON TABLE  public.system_oper_log                IS '操作日志记录';
COMMENT ON COLUMN public.system_oper_log.id             IS '日志主键';
COMMENT ON COLUMN public.system_oper_log.title          IS '模块标题';
COMMENT ON COLUMN public.system_oper_log.business_type  IS '业务类型（0其它 1新增 2修改 3删除 4授权 5导出 6导入 7强退 8生成代码 9清空数据）';
COMMENT ON COLUMN public.system_oper_log.method         IS '方法名称';
COMMENT ON COLUMN public.system_oper_log.request_method IS '请求方式';
COMMENT ON COLUMN public.system_oper_log.operator_type  IS '操作类别（0其它 1后台用户 2手机端用户）';
COMMENT ON COLUMN public.system_oper_log.oper_name      IS '操作人员';
COMMENT ON COLUMN public.system_oper_log.dept_name      IS '部门名称';
COMMENT ON COLUMN public.system_oper_log.oper_url       IS '请求URL';
COMMENT ON COLUMN public.system_oper_log.oper_ip        IS '操作地址';
COMMENT ON COLUMN public.system_oper_log.oper_location  IS '操作地点';
COMMENT ON COLUMN public.system_oper_log.oper_param     IS '请求参数';
COMMENT ON COLUMN public.system_oper_log.json_result    IS '返回结果';
COMMENT ON COLUMN public.system_oper_log.status         IS '操作状态（0正常 1异常）';
COMMENT ON COLUMN public.system_oper_log.error_msg      IS '错误消息';
COMMENT ON COLUMN public.system_oper_log.cost_time      IS '耗时（毫秒）';
COMMENT ON COLUMN public.system_oper_log.create_time    IS '操作时间';

-- ----------------------------
-- 2. 系统访问记录表
-- ----------------------------
DROP TABLE IF EXISTS public.system_login_log;
CREATE TABLE public.system_login_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        CHARACTER VARYING(50)  NOT NULL DEFAULT '',               -- 用户账号
    login_ip        CHARACTER VARYING(128) NOT NULL DEFAULT '',               -- 登录IP地址
    login_location  CHARACTER VARYING(255)          DEFAULT '',               -- 登录地点
    browser         CHARACTER VARYING(50)           DEFAULT '',               -- 浏览器类型
    os              CHARACTER VARYING(50)           DEFAULT '',               -- 操作系统
    status          SMALLINT               NOT NULL DEFAULT 0,                -- 登录状态 (0=成功, 1=失败)
    msg             CHARACTER VARYING(255)          DEFAULT '',               -- 提示消息
    create_time     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP -- 访问时间
);

COMMENT ON TABLE  public.system_login_log                IS '系统访问记录';
COMMENT ON COLUMN public.system_login_log.id             IS '访问ID';
COMMENT ON COLUMN public.system_login_log.username       IS '用户账号';
COMMENT ON COLUMN public.system_login_log.login_ip       IS '登录IP地址';
COMMENT ON COLUMN public.system_login_log.login_location IS '登录地点';
COMMENT ON COLUMN public.system_login_log.browser        IS '浏览器类型';
COMMENT ON COLUMN public.system_login_log.os             IS '操作系统';
COMMENT ON COLUMN public.system_login_log.status         IS '登录状态（0成功 1失败）';
COMMENT ON COLUMN public.system_login_log.msg            IS '提示消息';
COMMENT ON COLUMN public.system_login_log.create_time    IS '访问时间';

-- ----------------------------
-- 3. 日志模块字典数据
-- ----------------------------
-- 业务类型字典
INSERT INTO public.system_dict_type (id, name, type, status, creator, create_time, updater, update_time)
VALUES (nextval('public.system_dict_type_id_seq'), '操作类型', 'sys_oper_type', 0, 'admin', now(), 'admin', now());

INSERT INTO public.system_dict_data (sort, label, value, dict_type, status, color_type, creator, create_time, updater, update_time)
VALUES 
(0, '其它', '0', 'sys_oper_type', 0, 'info', 'admin', now(), 'admin', now()),
(1, '新增', '1', 'sys_oper_type', 0, 'success', 'admin', now(), 'admin', now()),
(2, '修改', '2', 'sys_oper_type', 0, 'warning', 'admin', now(), 'admin', now()),
(3, '删除', '3', 'sys_oper_type', 0, 'danger', 'admin', now(), 'admin', now()),
(4, '授权', '4', 'sys_oper_type', 0, 'primary', 'admin', now(), 'admin', now()),
(5, '导出', '5', 'sys_oper_type', 0, 'info', 'admin', now(), 'admin', now()),
(6, '导入', '6', 'sys_oper_type', 0, 'info', 'admin', now(), 'admin', now()),
(7, '强退', '7', 'sys_oper_type', 0, 'danger', 'admin', now(), 'admin', now()),
(8, '生成代码', '8', 'sys_oper_type', 0, 'info', 'admin', now(), 'admin', now()),
(9, '清空数据', '9', 'sys_oper_type', 0, 'danger', 'admin', now(), 'admin', now());

-- 成功/失败状态字典
INSERT INTO public.system_dict_type (id, name, type, status, creator, create_time, updater, update_time, remark)
VALUES (nextval('public.system_dict_type_id_seq'), '成功/失败状态', 'sys_common_status', 0, 'admin', now(), 'admin', now(), '登录/操作状态（成功/失败）');

INSERT INTO public.system_dict_data (sort, label, value, dict_type, status, color_type, creator, create_time, updater, update_time)
VALUES 
(0, '成功', '0', 'sys_common_status', 0, 'success', 'admin', now(), 'admin', now()),
(1, '失败', '1', 'sys_common_status', 0, 'danger', 'admin', now(), 'admin', now());
