spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.20:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: 192.168.100.20:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP


# 日志文件配置
logging:
  level:
    root: INFO # 全局日志级别
    # 特定包日志级别
    org.springframework.web: DEBUG
    org.mybatis: DEBUG

