# ===================================================================
# 定时任务服务 - 开发环境配置
# ===================================================================

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.20:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: 192.168.100.20:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP

# ===================================================================
# 日志级别配置
# ===================================================================
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.mybatis: DEBUG