spring:
  cloud:
    gateway:
      server:
        webflux:
          # 路由发现配置
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

    nacos:
      discovery:
        server-addr: 192.168.100.20:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: 192.168.100.20:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
