# ===================================================================
# 示例服务 - 开发环境配置
# ===================================================================

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.20:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: 192.168.100.20:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
    sentinel:
      transport:
        dashboard: 192.168.100.20:8858

start:
  log:
    remote:
      enabled: true
