# ===================================================================
# 示例服务 - 主配置文件
# ===================================================================
# 说明：演示服务，用于展示框架功能和开发示例
# ===================================================================

spring:
  application:
    name: demo-service
  profiles:
    active: @profiles.active@
  config:
    import:
      - optional:application-${spring.profiles.active}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml

server:
  port: 58082

# ===================================================================
# 接口文档配置
# ===================================================================
springdoc:
  api-docs:
    path: /admin/demo/v3/api-docs