# ===================================================================
# 演示服务 - 主配置文件
# ===================================================================

server:
  port: 58082

spring:
  application:
    name: demo-service
  profiles:
    active: @profiles.active@
  config:
    import:
      - optional:application-${spring.profiles.active}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  threads:
    virtual:
      enabled: true

seata:
  client:
    undo:
      log-serialization: fastjson
start:
  log:
    remote:
      enabled: true


# ===================================================================
# 接口文档配置
# ===================================================================
springdoc:
  api-docs:
    path: /admin/demo/v3/api-docs
