# ===================================================================
# 定时任务服务 - 主配置文件
# ===================================================================
# 说明：基于 SnailJob 的分布式定时任务调度服务
# ===================================================================

spring:
  application:
    name: job-service
  profiles:
    active: @profiles.active@
  config:
    import:
      - optional:application-${spring.profiles.active}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
  threads:
    virtual:
      enabled: true

server:
  port: 58083

# ===================================================================
# Feign 客户端配置
# ===================================================================
feign:
  client:
    config:
      default:
        loggerLevel: BASIC
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

# ===================================================================
# SnailJob 定时任务配置
# ===================================================================
snail-job:
  enabled: true
  server:
    host: 192.168.100.20
    port: 17888
  namespace: 764d604ec6fc45f68cd92514c40e9e1a
  group: default
  token: SJ_Wyz3dmsdbDOkDujOTSSoBjGQP1BMsVnj
  port: 17899