spring:
  application:
    name: gateway-service
  profiles:
    active: @profiles.active@  # 使用Maven过滤 激活对应环境的配置
  config:
    import:
      - optional:application-${spring.profiles.active}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml # 加载【Nacos】的配置
  main:
    allow-circular-references: true # 允许循环依赖

logging:
  level:
    com.alibaba.nacos: WARN
    com.alibaba.nacos.client.config.impl.ClientWorker: ERROR
    com.alibaba.nacos.client.naming: WARN
server:
  port: 48080